# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SwiftExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftExample
  pod 'ves-sample', :podspec => 'https://raw.githubusercontent.com/VIDY/ios-sample-vidy-sdk/master/ves-sample.podspec'

end
